{% set name = "pomegranate" %}
{% set version = "0.14.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  # use github archive as the sdist is missing pyx files
  url: https://files.pythonhosted.org/packages/51/66/e8d7b24462d6ba96a83e5135aeed202d72993d4d70b6c91301a0ffae365b/{{ name }}-{{ version }}.tar.gz
  # Doesn't seem to be getting tagged correctly
# url: https://github.com/jmschrei/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 72bb4b1016e83e43989e1cf6bd139b2faa85d0ee09faeed83055731ae9991330

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - scipy >=0.17.0
  run:
    - joblib >=0.9.0b4
    - networkx >=2.0
    - {{ pin_compatible("numpy") }}
    - python
    - pyyaml
    - scipy >=0.17.0

test:
  imports:
    - pomegranate
    - pomegranate.distributions

about:
  home: "http://pypi.python.org/pypi/pomegranate/"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "Pomegranate is a graphical models library for Python, implemented in Cython for speed."
  doc_url: "https://pomegranate.readthedocs.io"
  dev_url: "https://github.com/jmschrei/pomegranate"

extra:
  recipe-maintainers:
    - micknudsen
