{% set name = "pomegranate" %}
{% set version = "0.14.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  # use github archive as the sdist is missing pyx files
  url: https://files.pythonhosted.org/packages/3b/b7/d5e1fdf988efb1d4293c681794bc48d2db3d4266aade82367d7b586fc6dd/{{ name }}-{{ version }}.tar.gz
# url: https://github.com/jmschrei/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 16c4f7e66142a03ca3701590dce8c674e13270936bb7270015a77627ece23433

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - scipy >=0.17.0
  run:
    - joblib >=0.9.0b4
    - networkx >=2.0
    - {{ pin_compatible("numpy") }}
    - python
    - pyyaml
    - scipy >=0.17.0

test:
  imports:
    - pomegranate
    - pomegranate.distributions

about:
  home: "http://pypi.python.org/pypi/pomegranate/"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "Pomegranate is a graphical models library for Python, implemented in Cython for speed."
  doc_url: "https://pomegranate.readthedocs.io"
  dev_url: "https://github.com/jmschrei/pomegranate"

extra:
  recipe-maintainers:
    - micknudsen
