{% set name = "pomegranate" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bffe01521e8783ef84cb60862ea60161c2130835868d8a37b7d79477b328ad8f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy >=1.22.2
    - scipy >=1.6.2
    - scikit-learn >=1.0.2
    - pytorch >=1.9.0
    - apricot-select >=0.6.1
    - networkx >=2.8.4

test:
  source_files:
    - tests
  imports:
    - pomegranate
    - pomegranate._utils
    - pomegranate.bayes_classifier
    - pomegranate.bayesian_network
    - pomegranate.distributions
    - pomegranate.factor_graph
    - pomegranate.gmm
    - pomegranate.hmm
    - pomegranate.kmeans
    - pomegranate.markov_chain
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/jmschrei/pomegranate
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A PyTorch implementation of probabilistic models.
  description: |
    pomegranate is a library for probabilistic modeling defined by its modular implementation and
    treatment of all models as the probability distributions they are. The modular implementation
    allows one to easily drop normal distributions into a mixture model to create a Gaussian mixture
    model just as easily as dropping a gamma and a Poisson distribution into a mixture model to create
    a heterogeneous mixture. But that's not all! Because each model is treated as a probability distribution,
    Bayesian networks can be dropped into a mixture just as easily as a normal distribution, and hidden Markov
    models can be dropped into Bayes classifiers to make a classifier over sequences. Together,
    these two design choices enable a flexibility not seen in any other probabilistic modeling package.
  doc_url: https://pomegranate.readthedocs.io
  dev_url: https://github.com/jmschrei/pomegranate

extra:
  recipe-maintainers:
    - micknudsen